[package]
cairo-version = "2.1.0-rc4"
description = "Implementations of a defi primitives for the Dojo framework"
name = "dojo_defi"
version = "0.2.1"

[dependencies]
# Next lines to be reverted once Cubit repo is updated.
# cubit = { git = "https://github.com/influenceth/cubit" }
cubit = {git = "https://github.com/ametel01/cubit.git"}
dojo = { path = "../dojo-core" }

[[target.dojo]]
