[package]
name = "dojo_defi"
version = "0.1.0"
description = "Implementations of a defi primitives for the Dojo framework"

[dependencies]
cubit = { git = "https://github.com/influenceth/cubit", version = "0.1.0" }
dojo_core = { path = "../dojo-core" }

[[target.dojo]]
