[package]
edition.workspace = true
name = "sozo-ops"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cainome.workspace = true
colored.workspace = true
dojo-types.workspace = true
dojo-utils.workspace = true
dojo-world = { workspace = true, features = [ "ipfs" ] }
futures.workspace = true
num-traits.workspace = true
scarb-interop.workspace = true
serde_json.workspace = true
sozo-voyager.workspace = true
sozo-walnut = { workspace = true, optional = true }
spinoff.workspace = true
starknet.workspace = true
starknet-crypto.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [ "time" ] }
tracing.workspace = true

dojo-test-utils = { workspace = true, features = [ "build-examples" ], optional = true }

[dev-dependencies]
dojo-test-utils = { workspace = true, features = [ "build-examples" ] }
katana-runner.workspace = true
scarb-metadata-ext.workspace = true
tokio.workspace = true

[features]
test-utils = [ "dep:dojo-test-utils" ]
walnut = [ "dep:sozo-walnut" ]

[package.metadata.cargo-machete]
ignored = ["sozo-walnut"]
